### ISSUE TITLE
jshannel origin is case-sensitive (while window.postMessage origin is not)

### ISSUE THREAD

**Issue by jmandel** [mozilla/jschannel#10]
The behavior of window.postMessage is to extract an origin from the URI provided, such that I can do either of the following:
1.  `target.postMessage("A message", "http://someORIGIN.com");`
2. `target.postMessage("A message", "http://someorigin.com");`

... but since `Channel.build` uses the `origin` parameter as the key to an associative array, if I build a channel with scope `http://someORIGIN.com`, it will fail to receive messages with `event.origin=="http://someorigin.com"`.

It might be worth normalizing the origin URI passed into `Channel.build`, e.g. by calling `toLowerCase()`.   Does this open up other issues I haven't thought of?  Sample patch below.

  -Josh

---

<pre>
From a50048a86d9022e34b66f50b831386e14b8a55f2 Mon Sep 17 00:00:00 2001
From: Josh Mandel <joshua.mandel@childrens.harvard.edu>
Date: Mon, 23 May 2011 11:34:53 -0700
Subject: [PATCH] normalize channel origin to lower-case

---
 src/jschannel.js |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/src/jschannel.js b/src/jschannel.js
index 6e6f6c0..f7a639e 100644
--- a/src/jschannel.js
+++ b/src/jschannel.js
@@ -248,7 +248,7 @@
                 if (cfg.origin === "*") validOrigin = true;
                 // allow valid domains under http and https.  Also, trim paths off otherwise valid origins.
                 else if (null !== (oMatch = cfg.origin.match(/^https?:\/\/(?:[-a-zA-Z0-9\.])+(?::\d+)?/))) {
-                    cfg.origin = oMatch[0];
+                    cfg.origin = oMatch[0].toLowerCase();
                     validOrigin = true;
                 }
             }
-- 
1.7.4.1
</pre>

**Comment by toolness** [comment]
Cool! Would you mind adding a test for this and issuing a pull request?

We've got some origin tests right around [here](https://github.com/mozilla/jschannel/blob/master/docs/index.html#L118).

**Comment by jmandel** [comment]
Pull request issued!

**Comment by lloyd** [comment]
holy shit.  this was fixed two years ago.
