### ISSUE TITLE
recursive data structure in params

### ISSUE THREAD

**Issue by edsu** [mozilla/jschannel#14]
I accidentally passed a recursive data structure to call, and got an exception that took me some time to understand:

``` javascript
chan.call({
  method: "highlight",
  params: window.getSelection(),
  success: function(v) {
    console.log("highlighted " + v);
  }
});
```

Which results in: 

```
Uncaught RangeError: Maximum call stack size exceeded
```

due to an infinite recursion in pruneFunctions.

**Comment by lloyd** [comment]
r+.  ty kindly. (especially for adding a test!)
